feat:#22 criação do metodo de atualização do estatus da transação
Fernnandez/riquinho-app pull request #24
Opened 2022-09-09 02:34 UTC by miguelgabriel01

Desenvolvimento do método de atualização do status de uma transação

2022-09-13 11:00 UTC, Fernnandez requested changes

2022-09-27 00:30 UTC, miguelgabriel01 commented on riquinho-api/.env.development
> +POSTGRES_PASSWORD=miguel
Como uso uma versão real do banco, irei ignorar esse arquivo no meu próximo commit

2022-09-27 00:31 UTC, miguelgabriel01 commented on riquinho-api/src/transacao/controllers/transacao.controller.ts
> +import { patch } from 'superagent';
Faz sim.  Mas logo após iriei verificar com mais calma.

2022-09-27 00:32 UTC, miguelgabriel01 commented on riquinho-api/src/transacao/services/transacao.service.ts
> +    updateTransacaoDto: CreateUpdateTransacaoDto,
Essa parte não consegui entender bem. Se possível, podemos falar em uma call sobre esse ponto.

2022-09-27 00:33 UTC, miguelgabriel01 commented on riquinho-api/src/transacao/services/transacao.service.ts
> +    } else {
Entendo. Nessa parte vale o conceito que vários caminhos podem chegar ao mesmo local. Esse tratamento é mais para o que chega no request.

2022-09-27 00:34 UTC, miguelgabriel01 commented on riquinho-api/src/transacao/services/transacao.service.ts
> +      console.log(messageErroUpdatestatus);
OK. nessa parte faltou conhecimento técnico da minha parte sobre o lançamento de exceções nessa tecnologia.

2022-09-27 00:35 UTC, miguelgabriel01 commented on riquinho-api/src/transacao/services/transacao.service.ts
> +/*   async updateStatus(
Possivelmente sim.

2022-09-30 13:32 UTC, Fernnandez commented on riquinho-api/src/transacao/services/transacao.service.ts
> +    updateTransacaoDto: CreateUpdateTransacaoDto,
O que acontece aqui é que o CreateUpdateTransacaoDto é apenas um Objeto de transferência de dados que imita a entidade Transacao, como nessa função você quer atualizar uma transação,e lá no controller você está recebendo o id dessa transação e buscando no banco, supostamente você pega uma instancia de Transacao e não de CreateUpdateTransacaoDto, faz sentido ?
Se não ficou  muito claro dps só me chamar que a gente olha pra esse tema

2022-09-30 13:37 UTC, Fernnandez commented on riquinho-api/src/transacao/services/transacao.service.ts
> +    } else {
Esse é um ponto interessante, quando eu digo que nunca será diferente, falo isso pois essa mesma verificação é feita lá no DTO, quando a gente usa o classValidador 
![image](https://user-images.githubusercontent.com/67211421/193281775-08926d2a-7b5a-4130-b56e-798a98d1eda3.png)
Esse @IsEnum() faz basicamente isso, verifica se o valor recebido realmente existe naquele conjunto de valores esperados

2022-09-30 13:38 UTC, Fernnandez reviewed
Só resolver o conflito no PR que eu aprovo @miguelgabriel01

2022-10-06 21:44 UTC, Fernnandez approved these changes

2022-10-06 21:45 UTC, merged