Update senha user
Fernnandez/riquinho-app pull request #48
Opened 2022-11-18 10:38 UTC by Pedrohsmarinho

referencia #40.

2022-11-18 16:45 UTC, Fernnandez requested changes

2022-11-18 16:45 UTC, Fernnandez commented on front/src/components/UpdateSenhaForm/UpdateSenhaForm.tsx
> +          <TextInput
Acho que faria sentido aqui já trocar pelo input de senha, o que acha ?
```suggestion
          <PasswordInput
```

2022-11-18 16:45 UTC, Fernnandez commented on front/src/components/UpdateSenhaForm/UpdateSenhaForm.tsx
> +            <TextInput
Acho que faria sentido aqui já trocar pelo input de senha, o que acha ?

2022-11-18 16:45 UTC, Fernnandez commented on front/src/pages/CustomPage/index.tsx
> +          // senha={data.data.Senha}
Esse comentário pode ser removido ?

2022-11-18 16:45 UTC, Fernnandez commented on front/src/services/user.ts
> +  dataS: { lastSenha: string; senha: string },
```suggestion
  data: { lastSenha: string; senha: string },
```

acho que aqui o parâmetro pode ser só data, o que acha ?

2022-11-19 23:17 UTC, Pedrohsmarinho commented on front/src/components/UpdateSenhaForm/UpdateSenhaForm.tsx
> +          <TextInput
Sim, concordo. inclusive se não mudou lá no de change Username vou alterar também.

2022-11-19 23:18 UTC, Pedrohsmarinho commented on front/src/services/user.ts
> +  dataS: { lastSenha: string; senha: string },
SIm, na versão que tenho tá data normal, foi minha dúvida de como chamar o dado lá no front. imaginei que precisava mudar pra nao conflitar com o findAllUsers mas não. vou ajustar isso.

2022-11-20 22:33 UTC, Fernnandez approved these changes

2022-11-20 22:37 UTC, merged